<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_Products LoansCredit CardsMobile Banki_3be752</name>
   <tag></tag>
   <elementGuidId>22ec23c2-dbf5-471d-b33f-b032646282d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-root > body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root/body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>c5334f5b-de58-42ec-9cac-6ad3b95beb12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Products LoansCredit CardsMobile BankingLogin arrow_back Loan ApplicationHi! Enter some details below to get started!Email Address of RequesterLoan Amount RequestedLoan Term13510Current Yearly Income (Before Taxes)AgeSubmit Loan Application Need a Loan?  Contact Us  UiBank v2020.4.4 </value>
      <webElementGuid>57cbd527-c4a9-4373-a6c0-fb61dde94c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/body[1]</value>
      <webElementGuid>32316aaf-0eef-4d85-8516-edd92f5a686c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-root/body</value>
      <webElementGuid>5a52a4c9-dc9d-4e46-b3c7-d1e7a64b47c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = ' Products LoansCredit CardsMobile BankingLogin arrow_back Loan ApplicationHi! Enter some details below to get started!Email Address of RequesterLoan Amount RequestedLoan Term13510Current Yearly Income (Before Taxes)AgeSubmit Loan Application Need a Loan?  Contact Us  UiBank v2020.4.4 ' or . = ' Products LoansCredit CardsMobile BankingLogin arrow_back Loan ApplicationHi! Enter some details below to get started!Email Address of RequesterLoan Amount RequestedLoan Term13510Current Yearly Income (Before Taxes)AgeSubmit Loan Application Need a Loan?  Contact Us  UiBank v2020.4.4 ')]</value>
      <webElementGuid>7e71e528-3de4-432c-8409-0323ab0ca1bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
