<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Current Yearly Income (Before Taxes)_income</name>
   <tag></tag>
   <elementGuidId>07c9fb3a-050c-4160-a741-b4b106eff8e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='income']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#income</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b3615f8-fbde-4c23-bdae-5c1e94d4a8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>3a80fcb0-7848-4eb1-9cef-a44e203f32ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>income</value>
      <webElementGuid>1cf9d907-69d8-4a81-bbaf-e9d2fc8ce2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>income</value>
      <webElementGuid>5fd1a605-a387-4d81-9bd8-dd93a752a75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>How much do you make before taxes a year?</value>
      <webElementGuid>afb68824-d609-4430-8089-c6d7094135cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>3438092a-943c-4ab0-b3b3-8ff6b74e5c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;income&quot;)</value>
      <webElementGuid>f96dd39e-fc41-4ca5-a52c-88e4dd5904b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='income']</value>
      <webElementGuid>afb1dc29-4836-4ca0-8ae4-2d65e19e634c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>014e4639-fa0c-4844-b0ad-f6861db46176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'income' and @name = 'income' and @placeholder = 'How much do you make before taxes a year?' and @type = 'number']</value>
      <webElementGuid>76c8854a-8622-401b-ba5d-de244a9e264d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
